### ISSUE TITLE
국민은행

### ISSUE THREAD

**Issue by ShapeLayer** [kowaku/astx#7]
아마도..씹히는듯.

**Comment by kowaku** [comment]
![image](https://user-images.githubusercontent.com/27746455/29000921-fbd9ee22-7ab5-11e7-933b-6212a9a6a17c.png)
That bank doesn't require ASTX. please check again.

**Comment by kowaku** [comment]
'국민은행' requires, that load port `55921` and `55922`. Multi port required.
![image](https://user-images.githubusercontent.com/27746455/29000944-7b2585ba-7ab6-11e7-9cbb-77068e1943da.png)

**Comment by kowaku** [comment]
![image](https://user-images.githubusercontent.com/27746455/29001093-140d2cc6-7aba-11e7-8877-0a17dc4aa4eb.png)
PASSED
